apiVersion: v1
kind: Service
metadata:
  name: jwks-server
  namespace: istio-jwt-demo
  labels:
    app: jwks-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: jwks-server
